// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: proto/secure_storage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Errors
type Answer int32

const (
	Answer_Ok               Answer = 0
	Answer_AlreadyExists    Answer = 1
	Answer_UserNotFound     Answer = 2
	Answer_IncorrectPwd     Answer = 3
	Answer_UnauthorizedUser Answer = 4
	Answer_NotFound         Answer = 5
)

// Enum value maps for Answer.
var (
	Answer_name = map[int32]string{
		0: "Ok",
		1: "AlreadyExists",
		2: "UserNotFound",
		3: "IncorrectPwd",
		4: "UnauthorizedUser",
		5: "NotFound",
	}
	Answer_value = map[string]int32{
		"Ok":               0,
		"AlreadyExists":    1,
		"UserNotFound":     2,
		"IncorrectPwd":     3,
		"UnauthorizedUser": 4,
		"NotFound":         5,
	}
)

func (x Answer) Enum() *Answer {
	p := new(Answer)
	*p = x
	return p
}

func (x Answer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Answer) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_secure_storage_proto_enumTypes[0].Descriptor()
}

func (Answer) Type() protoreflect.EnumType {
	return &file_proto_secure_storage_proto_enumTypes[0]
}

func (x Answer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Answer.Descriptor instead.
func (Answer) EnumDescriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{0}
}

// Check service health
type CheckServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckServiceRequest) Reset() {
	*x = CheckServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckServiceRequest) ProtoMessage() {}

func (x *CheckServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckServiceRequest.ProtoReflect.Descriptor instead.
func (*CheckServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{0}
}

type CheckServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Up bool `protobuf:"varint,1,opt,name=up,proto3" json:"up,omitempty"`
}

func (x *CheckServiceResponse) Reset() {
	*x = CheckServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckServiceResponse) ProtoMessage() {}

func (x *CheckServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckServiceResponse.ProtoReflect.Descriptor instead.
func (*CheckServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{1}
}

func (x *CheckServiceResponse) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

// Register User
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SecondName string `protobuf:"bytes,4,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

type RegisterUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	User     *User  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer Answer `protobuf:"varint,1,opt,name=answer,proto3,enum=secure_storage.Answer" json:"answer,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterUserResponse) GetAnswer() Answer {
	if x != nil {
		return x.Answer
	}
	return Answer_Ok
}

func (x *RegisterUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Auth User
type AuthUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AuthUserRequest) Reset() {
	*x = AuthUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserRequest) ProtoMessage() {}

func (x *AuthUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserRequest.ProtoReflect.Descriptor instead.
func (*AuthUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{5}
}

func (x *AuthUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AuthUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer Answer `protobuf:"varint,1,opt,name=answer,proto3,enum=secure_storage.Answer" json:"answer,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AuthUserResponse) Reset() {
	*x = AuthUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserResponse) ProtoMessage() {}

func (x *AuthUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserResponse.ProtoReflect.Descriptor instead.
func (*AuthUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{6}
}

func (x *AuthUserResponse) GetAnswer() Answer {
	if x != nil {
		return x.Answer
	}
	return Answer_Ok
}

func (x *AuthUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Save User Card
type Expired struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year  string `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Month string `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
}

func (x *Expired) Reset() {
	*x = Expired{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expired) ProtoMessage() {}

func (x *Expired) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expired.ProtoReflect.Descriptor instead.
func (*Expired) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{7}
}

func (x *Expired) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *Expired) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardNumber string   `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Cvv        int32    `protobuf:"varint,2,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Cardholder string   `protobuf:"bytes,3,opt,name=cardholder,proto3" json:"cardholder,omitempty"`
	Expired    *Expired `protobuf:"bytes,4,opt,name=expired,proto3" json:"expired,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{8}
}

func (x *Card) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *Card) GetCvv() int32 {
	if x != nil {
		return x.Cvv
	}
	return 0
}

func (x *Card) GetCardholder() string {
	if x != nil {
		return x.Cardholder
	}
	return ""
}

func (x *Card) GetExpired() *Expired {
	if x != nil {
		return x.Expired
	}
	return nil
}

type SaveUserCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card *Card `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *SaveUserCardRequest) Reset() {
	*x = SaveUserCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveUserCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserCardRequest) ProtoMessage() {}

func (x *SaveUserCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserCardRequest.ProtoReflect.Descriptor instead.
func (*SaveUserCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{9}
}

func (x *SaveUserCardRequest) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type SaveUserCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer Answer `protobuf:"varint,1,opt,name=answer,proto3,enum=secure_storage.Answer" json:"answer,omitempty"`
}

func (x *SaveUserCardResponse) Reset() {
	*x = SaveUserCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveUserCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserCardResponse) ProtoMessage() {}

func (x *SaveUserCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserCardResponse.ProtoReflect.Descriptor instead.
func (*SaveUserCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{10}
}

func (x *SaveUserCardResponse) GetAnswer() Answer {
	if x != nil {
		return x.Answer
	}
	return Answer_Ok
}

// Get User Cards
type GetUserCardsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserCardsRequest) Reset() {
	*x = GetUserCardsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCardsRequest) ProtoMessage() {}

func (x *GetUserCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCardsRequest.ProtoReflect.Descriptor instead.
func (*GetUserCardsRequest) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{11}
}

type GetUserCardsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards  []*Card `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	Answer Answer  `protobuf:"varint,2,opt,name=answer,proto3,enum=secure_storage.Answer" json:"answer,omitempty"`
}

func (x *GetUserCardsResponse) Reset() {
	*x = GetUserCardsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCardsResponse) ProtoMessage() {}

func (x *GetUserCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCardsResponse.ProtoReflect.Descriptor instead.
func (*GetUserCardsResponse) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *GetUserCardsResponse) GetAnswer() Answer {
	if x != nil {
		return x.Answer
	}
	return Answer_Ok
}

// Save User Credentials
type Credentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source   string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Login    string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{13}
}

func (x *Credentials) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Credentials) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SaveUserCredentialsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Credentials *Credentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
}

func (x *SaveUserCredentialsRequest) Reset() {
	*x = SaveUserCredentialsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveUserCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserCredentialsRequest) ProtoMessage() {}

func (x *SaveUserCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserCredentialsRequest.ProtoReflect.Descriptor instead.
func (*SaveUserCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{14}
}

func (x *SaveUserCredentialsRequest) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type SaveUserCredentialsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer Answer `protobuf:"varint,1,opt,name=answer,proto3,enum=secure_storage.Answer" json:"answer,omitempty"`
}

func (x *SaveUserCredentialsResponse) Reset() {
	*x = SaveUserCredentialsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveUserCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserCredentialsResponse) ProtoMessage() {}

func (x *SaveUserCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserCredentialsResponse.ProtoReflect.Descriptor instead.
func (*SaveUserCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{15}
}

func (x *SaveUserCredentialsResponse) GetAnswer() Answer {
	if x != nil {
		return x.Answer
	}
	return Answer_Ok
}

// Get User Credentials
type GetUserCredentialsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserCredentialsRequest) Reset() {
	*x = GetUserCredentialsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCredentialsRequest) ProtoMessage() {}

func (x *GetUserCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetUserCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{16}
}

type GetUserCredentialsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Credentials []*Credentials `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	Answer      Answer         `protobuf:"varint,2,opt,name=answer,proto3,enum=secure_storage.Answer" json:"answer,omitempty"`
}

func (x *GetUserCredentialsResponse) Reset() {
	*x = GetUserCredentialsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCredentialsResponse) ProtoMessage() {}

func (x *GetUserCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetUserCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserCredentialsResponse) GetCredentials() []*Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *GetUserCredentialsResponse) GetAnswer() Answer {
	if x != nil {
		return x.Answer
	}
	return Answer_Ok
}

// Save User Plain
type Plain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	BodyText string `protobuf:"bytes,2,opt,name=body_text,json=bodyText,proto3" json:"body_text,omitempty"`
}

func (x *Plain) Reset() {
	*x = Plain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plain) ProtoMessage() {}

func (x *Plain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plain.ProtoReflect.Descriptor instead.
func (*Plain) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{18}
}

func (x *Plain) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Plain) GetBodyText() string {
	if x != nil {
		return x.BodyText
	}
	return ""
}

type SaveUserPlainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plain *Plain `protobuf:"bytes,1,opt,name=plain,proto3" json:"plain,omitempty"`
}

func (x *SaveUserPlainRequest) Reset() {
	*x = SaveUserPlainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveUserPlainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserPlainRequest) ProtoMessage() {}

func (x *SaveUserPlainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserPlainRequest.ProtoReflect.Descriptor instead.
func (*SaveUserPlainRequest) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{19}
}

func (x *SaveUserPlainRequest) GetPlain() *Plain {
	if x != nil {
		return x.Plain
	}
	return nil
}

type SaveUserPlainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer Answer `protobuf:"varint,1,opt,name=answer,proto3,enum=secure_storage.Answer" json:"answer,omitempty"`
}

func (x *SaveUserPlainResponse) Reset() {
	*x = SaveUserPlainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveUserPlainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserPlainResponse) ProtoMessage() {}

func (x *SaveUserPlainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserPlainResponse.ProtoReflect.Descriptor instead.
func (*SaveUserPlainResponse) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{20}
}

func (x *SaveUserPlainResponse) GetAnswer() Answer {
	if x != nil {
		return x.Answer
	}
	return Answer_Ok
}

type GetUserPlainsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserPlainsRequest) Reset() {
	*x = GetUserPlainsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPlainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPlainsRequest) ProtoMessage() {}

func (x *GetUserPlainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPlainsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPlainsRequest) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{21}
}

type GetUserPlainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plains []*Plain `protobuf:"bytes,1,rep,name=plains,proto3" json:"plains,omitempty"`
	Answer Answer   `protobuf:"varint,2,opt,name=answer,proto3,enum=secure_storage.Answer" json:"answer,omitempty"`
}

func (x *GetUserPlainResponse) Reset() {
	*x = GetUserPlainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPlainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPlainResponse) ProtoMessage() {}

func (x *GetUserPlainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPlainResponse.ProtoReflect.Descriptor instead.
func (*GetUserPlainResponse) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserPlainResponse) GetPlains() []*Plain {
	if x != nil {
		return x.Plains
	}
	return nil
}

func (x *GetUserPlainResponse) GetAnswer() Answer {
	if x != nil {
		return x.Answer
	}
	return Answer_Ok
}

// User Binary
type SaveUserBinaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Binary []byte `protobuf:"bytes,2,opt,name=binary,proto3" json:"binary,omitempty"`
}

func (x *SaveUserBinaryRequest) Reset() {
	*x = SaveUserBinaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveUserBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserBinaryRequest) ProtoMessage() {}

func (x *SaveUserBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserBinaryRequest.ProtoReflect.Descriptor instead.
func (*SaveUserBinaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{23}
}

func (x *SaveUserBinaryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveUserBinaryRequest) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

type SaveUserBinaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer Answer `protobuf:"varint,1,opt,name=answer,proto3,enum=secure_storage.Answer" json:"answer,omitempty"`
}

func (x *SaveUserBinaryResponse) Reset() {
	*x = SaveUserBinaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveUserBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserBinaryResponse) ProtoMessage() {}

func (x *SaveUserBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserBinaryResponse.ProtoReflect.Descriptor instead.
func (*SaveUserBinaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{24}
}

func (x *SaveUserBinaryResponse) GetAnswer() Answer {
	if x != nil {
		return x.Answer
	}
	return Answer_Ok
}

type GetUserBinaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetUserBinaryRequest) Reset() {
	*x = GetUserBinaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBinaryRequest) ProtoMessage() {}

func (x *GetUserBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBinaryRequest.ProtoReflect.Descriptor instead.
func (*GetUserBinaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{25}
}

func (x *GetUserBinaryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetUserBinaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Binary []byte `protobuf:"bytes,2,opt,name=binary,proto3" json:"binary,omitempty"`
	Answer Answer `protobuf:"varint,3,opt,name=answer,proto3,enum=secure_storage.Answer" json:"answer,omitempty"`
}

func (x *GetUserBinaryResponse) Reset() {
	*x = GetUserBinaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBinaryResponse) ProtoMessage() {}

func (x *GetUserBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBinaryResponse.ProtoReflect.Descriptor instead.
func (*GetUserBinaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{26}
}

func (x *GetUserBinaryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserBinaryResponse) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *GetUserBinaryResponse) GetAnswer() Answer {
	if x != nil {
		return x.Answer
	}
	return Answer_Ok
}

type GetUserBinaryListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserBinaryListRequest) Reset() {
	*x = GetUserBinaryListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBinaryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBinaryListRequest) ProtoMessage() {}

func (x *GetUserBinaryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBinaryListRequest.ProtoReflect.Descriptor instead.
func (*GetUserBinaryListRequest) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{27}
}

type GetUserBinaryListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names  []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Answer Answer   `protobuf:"varint,2,opt,name=answer,proto3,enum=secure_storage.Answer" json:"answer,omitempty"`
}

func (x *GetUserBinaryListResponse) Reset() {
	*x = GetUserBinaryListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_secure_storage_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBinaryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBinaryListResponse) ProtoMessage() {}

func (x *GetUserBinaryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secure_storage_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBinaryListResponse.ProtoReflect.Descriptor instead.
func (*GetUserBinaryListResponse) Descriptor() ([]byte, []int) {
	return file_proto_secure_storage_proto_rawDescGZIP(), []int{28}
}

func (x *GetUserBinaryListResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *GetUserBinaryListResponse) GetAnswer() Answer {
	if x != nil {
		return x.Answer
	}
	return Answer_Ok
}

var File_proto_secure_storage_proto protoreflect.FileDescriptor

var file_proto_secure_storage_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x73, 0x65,
	0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x22, 0x15, 0x0a, 0x13,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x75,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x75, 0x70, 0x22, 0x3b, 0x0a, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x71, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x28, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x5c, 0x0a, 0x14, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x06, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x43, 0x0a, 0x0f, 0x41, 0x75, 0x74,
	0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x58,
	0x0a, 0x10, 0x41, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x33, 0x0a, 0x07, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x22, 0x8c, 0x01,
	0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x72,
	0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x76, 0x76, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x76, 0x76, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x72,
	0x64, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x61, 0x72, 0x64, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x07, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x65, 0x63,
	0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x64, 0x52, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x22, 0x3f, 0x0a, 0x13,
	0x53, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x46, 0x0a,
	0x14, 0x53, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x06, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x72, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73,
	0x12, 0x2e, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x16, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x22, 0x57, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x5b, 0x0a, 0x1a, 0x53, 0x61, 0x76,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x22, 0x4d, 0x0a, 0x1b, 0x53, 0x61, 0x76, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x06, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x1b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x8b, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x73, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73,
	0x12, 0x2e, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x16, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x22, 0x3a, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x64, 0x79, 0x54, 0x65, 0x78, 0x74, 0x22, 0x43, 0x0a, 0x14,
	0x53, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x69,
	0x6e, 0x22, 0x47, 0x0a, 0x15, 0x53, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x61, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x65, 0x63,
	0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x75, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x70, 0x6c,
	0x61, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x63,
	0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x69,
	0x6e, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x65, 0x63, 0x75,
	0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x43, 0x0a, 0x15, 0x53, 0x61, 0x76,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0x48,
	0x0a, 0x16, 0x53, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72,
	0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x73, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x2e, 0x0a, 0x06, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x65, 0x63, 0x75,
	0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x61, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72,
	0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2a, 0x6b, 0x0a, 0x06, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x6c,
	0x72, 0x65, 0x61, 0x64, 0x79, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x10, 0x01, 0x12, 0x10, 0x0a,
	0x0c, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x02, 0x12,
	0x10, 0x0a, 0x0c, 0x49, 0x6e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x50, 0x77, 0x64, 0x10,
	0x03, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x6e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x46, 0x6f,
	0x75, 0x6e, 0x64, 0x10, 0x05, 0x32, 0x8b, 0x09, 0x0a, 0x0d, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x59, 0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x23, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65,
	0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x59, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x23, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65,
	0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a,
	0x08, 0x41, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x73, 0x65, 0x63, 0x75,
	0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x65, 0x63,
	0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0c,
	0x53, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x12, 0x23, 0x2e, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x61,
	0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x23, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65,
	0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x6e, 0x0a, 0x13, 0x53, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x2a, 0x2e, 0x73, 0x65, 0x63, 0x75,
	0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x6b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x29, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72,
	0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5c, 0x0a, 0x0d, 0x53, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x69, 0x6e,
	0x12, 0x24, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x6c, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x24,
	0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x0e, 0x53, 0x61,
	0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x25, 0x2e, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x61,
	0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x24, 0x2e, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28,
	0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72,
	0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x16, 0x5a, 0x14, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_secure_storage_proto_rawDescOnce sync.Once
	file_proto_secure_storage_proto_rawDescData = file_proto_secure_storage_proto_rawDesc
)

func file_proto_secure_storage_proto_rawDescGZIP() []byte {
	file_proto_secure_storage_proto_rawDescOnce.Do(func() {
		file_proto_secure_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_secure_storage_proto_rawDescData)
	})
	return file_proto_secure_storage_proto_rawDescData
}

var file_proto_secure_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_secure_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_secure_storage_proto_goTypes = []interface{}{
	(Answer)(0),                         // 0: secure_storage.Answer
	(*CheckServiceRequest)(nil),         // 1: secure_storage.CheckServiceRequest
	(*CheckServiceResponse)(nil),        // 2: secure_storage.CheckServiceResponse
	(*User)(nil),                        // 3: secure_storage.User
	(*RegisterUserRequest)(nil),         // 4: secure_storage.RegisterUserRequest
	(*RegisterUserResponse)(nil),        // 5: secure_storage.RegisterUserResponse
	(*AuthUserRequest)(nil),             // 6: secure_storage.AuthUserRequest
	(*AuthUserResponse)(nil),            // 7: secure_storage.AuthUserResponse
	(*Expired)(nil),                     // 8: secure_storage.Expired
	(*Card)(nil),                        // 9: secure_storage.Card
	(*SaveUserCardRequest)(nil),         // 10: secure_storage.SaveUserCardRequest
	(*SaveUserCardResponse)(nil),        // 11: secure_storage.SaveUserCardResponse
	(*GetUserCardsRequest)(nil),         // 12: secure_storage.GetUserCardsRequest
	(*GetUserCardsResponse)(nil),        // 13: secure_storage.GetUserCardsResponse
	(*Credentials)(nil),                 // 14: secure_storage.Credentials
	(*SaveUserCredentialsRequest)(nil),  // 15: secure_storage.SaveUserCredentialsRequest
	(*SaveUserCredentialsResponse)(nil), // 16: secure_storage.SaveUserCredentialsResponse
	(*GetUserCredentialsRequest)(nil),   // 17: secure_storage.GetUserCredentialsRequest
	(*GetUserCredentialsResponse)(nil),  // 18: secure_storage.GetUserCredentialsResponse
	(*Plain)(nil),                       // 19: secure_storage.Plain
	(*SaveUserPlainRequest)(nil),        // 20: secure_storage.SaveUserPlainRequest
	(*SaveUserPlainResponse)(nil),       // 21: secure_storage.SaveUserPlainResponse
	(*GetUserPlainsRequest)(nil),        // 22: secure_storage.GetUserPlainsRequest
	(*GetUserPlainResponse)(nil),        // 23: secure_storage.GetUserPlainResponse
	(*SaveUserBinaryRequest)(nil),       // 24: secure_storage.SaveUserBinaryRequest
	(*SaveUserBinaryResponse)(nil),      // 25: secure_storage.SaveUserBinaryResponse
	(*GetUserBinaryRequest)(nil),        // 26: secure_storage.GetUserBinaryRequest
	(*GetUserBinaryResponse)(nil),       // 27: secure_storage.GetUserBinaryResponse
	(*GetUserBinaryListRequest)(nil),    // 28: secure_storage.GetUserBinaryListRequest
	(*GetUserBinaryListResponse)(nil),   // 29: secure_storage.GetUserBinaryListResponse
}
var file_proto_secure_storage_proto_depIdxs = []int32{
	3,  // 0: secure_storage.RegisterUserRequest.user:type_name -> secure_storage.User
	0,  // 1: secure_storage.RegisterUserResponse.answer:type_name -> secure_storage.Answer
	0,  // 2: secure_storage.AuthUserResponse.answer:type_name -> secure_storage.Answer
	8,  // 3: secure_storage.Card.expired:type_name -> secure_storage.Expired
	9,  // 4: secure_storage.SaveUserCardRequest.card:type_name -> secure_storage.Card
	0,  // 5: secure_storage.SaveUserCardResponse.answer:type_name -> secure_storage.Answer
	9,  // 6: secure_storage.GetUserCardsResponse.cards:type_name -> secure_storage.Card
	0,  // 7: secure_storage.GetUserCardsResponse.answer:type_name -> secure_storage.Answer
	14, // 8: secure_storage.SaveUserCredentialsRequest.credentials:type_name -> secure_storage.Credentials
	0,  // 9: secure_storage.SaveUserCredentialsResponse.answer:type_name -> secure_storage.Answer
	14, // 10: secure_storage.GetUserCredentialsResponse.credentials:type_name -> secure_storage.Credentials
	0,  // 11: secure_storage.GetUserCredentialsResponse.answer:type_name -> secure_storage.Answer
	19, // 12: secure_storage.SaveUserPlainRequest.plain:type_name -> secure_storage.Plain
	0,  // 13: secure_storage.SaveUserPlainResponse.answer:type_name -> secure_storage.Answer
	19, // 14: secure_storage.GetUserPlainResponse.plains:type_name -> secure_storage.Plain
	0,  // 15: secure_storage.GetUserPlainResponse.answer:type_name -> secure_storage.Answer
	0,  // 16: secure_storage.SaveUserBinaryResponse.answer:type_name -> secure_storage.Answer
	0,  // 17: secure_storage.GetUserBinaryResponse.answer:type_name -> secure_storage.Answer
	0,  // 18: secure_storage.GetUserBinaryListResponse.answer:type_name -> secure_storage.Answer
	1,  // 19: secure_storage.SecureStorage.CheckService:input_type -> secure_storage.CheckServiceRequest
	4,  // 20: secure_storage.SecureStorage.RegisterUser:input_type -> secure_storage.RegisterUserRequest
	6,  // 21: secure_storage.SecureStorage.AuthUser:input_type -> secure_storage.AuthUserRequest
	10, // 22: secure_storage.SecureStorage.SaveUserCard:input_type -> secure_storage.SaveUserCardRequest
	12, // 23: secure_storage.SecureStorage.GetUserCards:input_type -> secure_storage.GetUserCardsRequest
	15, // 24: secure_storage.SecureStorage.SaveUserCredentials:input_type -> secure_storage.SaveUserCredentialsRequest
	17, // 25: secure_storage.SecureStorage.GetUserCredentials:input_type -> secure_storage.GetUserCredentialsRequest
	20, // 26: secure_storage.SecureStorage.SaveUserPlain:input_type -> secure_storage.SaveUserPlainRequest
	22, // 27: secure_storage.SecureStorage.GetUserPlains:input_type -> secure_storage.GetUserPlainsRequest
	24, // 28: secure_storage.SecureStorage.SaveUserBinary:input_type -> secure_storage.SaveUserBinaryRequest
	26, // 29: secure_storage.SecureStorage.GetUserBinary:input_type -> secure_storage.GetUserBinaryRequest
	28, // 30: secure_storage.SecureStorage.GetUserBinaryList:input_type -> secure_storage.GetUserBinaryListRequest
	2,  // 31: secure_storage.SecureStorage.CheckService:output_type -> secure_storage.CheckServiceResponse
	5,  // 32: secure_storage.SecureStorage.RegisterUser:output_type -> secure_storage.RegisterUserResponse
	7,  // 33: secure_storage.SecureStorage.AuthUser:output_type -> secure_storage.AuthUserResponse
	11, // 34: secure_storage.SecureStorage.SaveUserCard:output_type -> secure_storage.SaveUserCardResponse
	13, // 35: secure_storage.SecureStorage.GetUserCards:output_type -> secure_storage.GetUserCardsResponse
	16, // 36: secure_storage.SecureStorage.SaveUserCredentials:output_type -> secure_storage.SaveUserCredentialsResponse
	18, // 37: secure_storage.SecureStorage.GetUserCredentials:output_type -> secure_storage.GetUserCredentialsResponse
	21, // 38: secure_storage.SecureStorage.SaveUserPlain:output_type -> secure_storage.SaveUserPlainResponse
	23, // 39: secure_storage.SecureStorage.GetUserPlains:output_type -> secure_storage.GetUserPlainResponse
	25, // 40: secure_storage.SecureStorage.SaveUserBinary:output_type -> secure_storage.SaveUserBinaryResponse
	27, // 41: secure_storage.SecureStorage.GetUserBinary:output_type -> secure_storage.GetUserBinaryResponse
	29, // 42: secure_storage.SecureStorage.GetUserBinaryList:output_type -> secure_storage.GetUserBinaryListResponse
	31, // [31:43] is the sub-list for method output_type
	19, // [19:31] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_secure_storage_proto_init() }
func file_proto_secure_storage_proto_init() {
	if File_proto_secure_storage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_secure_storage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expired); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveUserCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveUserCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCardsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCardsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Credentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveUserCredentialsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveUserCredentialsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCredentialsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCredentialsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveUserPlainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveUserPlainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPlainsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPlainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveUserBinaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveUserBinaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBinaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBinaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBinaryListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_secure_storage_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBinaryListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_secure_storage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_secure_storage_proto_goTypes,
		DependencyIndexes: file_proto_secure_storage_proto_depIdxs,
		EnumInfos:         file_proto_secure_storage_proto_enumTypes,
		MessageInfos:      file_proto_secure_storage_proto_msgTypes,
	}.Build()
	File_proto_secure_storage_proto = out.File
	file_proto_secure_storage_proto_rawDesc = nil
	file_proto_secure_storage_proto_goTypes = nil
	file_proto_secure_storage_proto_depIdxs = nil
}
